<%@page import="com.sap.core.odata.processor.jpa.api.ODataJPAContext"%>
<%@page import="java.util.List"%>
<%@page import="javax.persistence.EntityManager"%>
<%@page import="javax.persistence.EntityManagerFactory"%>
<%@page import="javax.persistence.Persistence"%>
<%@page import="javax.persistence.Query"%>
<%@page	import="com.sap.core.odata.processor.ref.JPAReferenceServiceFactory"%>
<%@page import="com.sap.core.odata.processor.ref.util.DataGenerator"%>

<%@ page language="java" contentType="text/html; charset=UTF-8"	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Data Generator</title>
</head>

<h2>Data Generator</h2>

<%
	EntityManagerFactory entityMangerFactory = (EntityManagerFactory) request.getSession().getAttribute("entityManagerFactory");
	EntityManager entityManager = (EntityManager) request.getSession().getAttribute("entityManager");
	DataGenerator dataGenerator = (DataGenerator) request.getSession().getAttribute("dataGenerator"); 
	// Check if data already exists
	Query q = entityManager.createQuery("SELECT COUNT(x) FROM SalesOrderHeader x");
	Number existingCount = (Number) q.getSingleResult();
	Number result1 = null;

	if (existingCount.intValue() == 0) { // Generate only if no data!
		dataGenerator.generate();
		result1 = (Number) q.getSingleResult();
		System.out.println("No data existing was existing.... Generated number of Items - " + result1);
	} else {
		System.err.println("Data already existing.... No Item generated by Data Generator !!");
	}
%>

<br>
<h2> Status of generation call - Generated number of items - <%=result1 != null ?result1:"None"%></h2>

<body>

</body>
</html>