<%@page import="com.sap.core.odata.processor.jpa.api.ODataJPAContext"%>
<%@page import="java.util.List"%>
<%@page import="javax.persistence.EntityManager"%>
<%@page import="javax.persistence.EntityManagerFactory"%>
<%@page import="javax.persistence.Persistence"%>
<%@page import="javax.persistence.Query"%>
<%@page	import="com.sap.core.odata.processor.ref.JPAReferenceServiceFactory"%>
<%@page import="com.sap.core.odata.processor.ref.util.DataGenerator"%>

<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Welcome to JPA implementation</title>
</head>
<body>
    <h1>SAP OData JPA library</h1>
    <hr />
	<h2>Reference Scenario</h2>
	<ul>
		<li><a href="SalesOrderProcessing.svc?_wadl" target="_blank">wadl</a></li>
		<li><a href="SalesOrderProcessing.svc/" target="_blank">service document</a></li>
		<li><a href="SalesOrderProcessing.svc/$metadata" target="_blank">metadata</a></li>
		<li><a href="SalesOrderProcessing.svc/SalesOrderHeaders" target="_blank">Simple Query</a></li>
		<li><a href="SalesOrderProcessing.svc/SalesOrderHeaders?$filter=buyerId eq 7" target="_blank">Query with $filter for buyerId 7</a></li>
	</ul>
	<hr />
		<h4>Reference Scenario Data Generation </h4>
        <form name="form1" method="get">
            <input type="hidden" name="button" value="Generate">
            <input type="submit" value="Generate Data" width="100%">
        </form>
        <br>
        <form name="form2" method="get">
            <input type="hidden" name="button" value="Clean">
            <input type="submit" value="   Clean Data  " width="100%">
        </form>
        
        <% 
        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("salesorderprocessing");
		EntityManager entityManager = entityManagerFactory.createEntityManager(); 
		DataGenerator dataGenerator = new DataGenerator(entityManager);

		Number result1 = null;
		Number existingCount = null;
		
		String msg = null;
       	if(request.getParameter("button") != null) {
       		if(request.getParameter("button").equalsIgnoreCase("Generate")){
        		Query q = entityManager.createQuery("SELECT COUNT(x) FROM SalesOrderHeader x");
				existingCount = (Number) q.getSingleResult();
				if (existingCount.intValue() == 0) { // Generate only if no data!
					dataGenerator.generate();
					result1 = (Number) q.getSingleResult();
					System.out.println("Data not existing earlier.... Generated number of Items - " + result1);
					msg = "Data not existing earlier.... Generated number of Items - " + result1;
				} else {
					System.err.println("Data already existing.... No Item generated by Data Generator !!");
					msg = "Data already existing.... No Item generated by Data Generator !!";
				}
       		} else{ //Clean
       			
       			// Check if data already exists
       			Query q = entityManager.createQuery("SELECT COUNT(x) FROM SalesOrderHeader x");
       			Number result = (Number) q.getSingleResult();
        		if (result.intValue() > 0) { // Generate only if no data!
        			dataGenerator.clean();
        		msg = "Data Cleaned. Number of items deleted - "+result;
        		}else{
        			msg = "No data existing.... Nothing to clean!!";
        		}
       		}
        %>
			<h5><%=(msg) %></h5>
        <%
            }
        %>
        
    </body>
</html>