package com.sap.core.odata.api.processor.feature;

public enum ProcessorFeature {
  BATCH, ENTITY, ENTITY_COMPLEX_PROPERTY, ENTITY_LINK, ENTITY_LINKS, ENTITY_MEDIA, ENTITY_SET, ENTITY_SIMPLE_PROPERTY, ENTITY_SIMPLE_PROPERTY_VALUE, FUNCTION_IMPORT, FUNCTION_IMPORT_VALUE, METDDATA, SERVICE_DOCUMENT
}
