package com.sap.core.odata.api.processor.feature;

/**
 * @author SAP AG
 */
public enum ProcessorFeature {
  SERVICE_DOCUMENT, METADATA, BATCH,
  ENTITY_SET, ENTITY, ENTITY_LINKS, ENTITY_LINK, ENTITY_MEDIA,
  ENTITY_COMPLEX_PROPERTY, ENTITY_SIMPLE_PROPERTY, ENTITY_SIMPLE_PROPERTY_VALUE,
  FUNCTION_IMPORT, FUNCTION_IMPORT_VALUE
}
