package com.sap.core.odata.processor.ref.test;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

import com.sap.core.odata.processor.ref.jpa.Material;
import com.sap.core.odata.processor.ref.jpa.SalesOrderHeader;
import com.sap.core.odata.processor.ref.jpa.SalesOrderItem;
import com.sap.core.odata.processor.ref.util.DataGenerator;

public class Test {

	/**
	 * @param args
	 */

	private static EntityManagerFactory emf;
	private static EntityManager em;

	public static void main(String[] args) {
		emf = Persistence.createEntityManagerFactory("salesorderprocessing");
		em = emf.createEntityManager();
		init( );
		String query = "SELECT R2.materialName, R2.typeCode FROM SalesOrderHeader e1 JOIN e1.salesOrderItem R1 JOIN R1.material R2";
		Query q = em.createQuery(query);
		
		//List<SalesOrderHeader> soh = q.getResultList();

		//List<SalesOrderItem> soi = q.getResultList();
		List<Object> m = q.getResultList();
		Object[] ar = (Object[]) m.get(0);
		System.out.println(ar[0]);
		
		clean( );

	}

	private static void init() {
		
		DataGenerator dataGenerator = new DataGenerator(em);

		Number result1 = null;
		Number existingCount = null;

		String msg = null;
		Query q = em
				.createQuery("SELECT COUNT(x) FROM SalesOrderHeader x");
		existingCount = (Number) q.getSingleResult();
		if (existingCount.intValue() == 0) { // Generate only if no data!
			dataGenerator.generate();
			result1 = (Number) q.getSingleResult();
			System.out
					.println("Data not existing earlier.... Generated number of Items - "
							+ result1);
			msg = result1 + " items generated ";

		} else {
			System.err
					.println("Data already existing.... No Item generated by Data Generator !!");
			msg = "Data exists. No Item generated !!";
		}

	}

	private static void clean() {
		DataGenerator dataGenerator = new DataGenerator(em);
		String msg = null;
		Query q = em
				.createQuery("SELECT COUNT(x) FROM SalesOrderHeader x");
		Number result = (Number) q.getSingleResult();
		if (result.intValue() > 0) { // Generate only if no data!
			dataGenerator.clean();
			msg = "Data Cleaned. " + result + " items cleaned.";
		} else {
			msg = " Nothing to clean!!";
		}
	}
}
