INSERT INTO AIRPORT (CODE, NAME, COUNTRY) VALUES ('MUC', 'Franz Josef Strauß', 'Germany');
INSERT INTO AIRPORT (CODE, NAME, COUNTRY) VALUES ('MIA', 'Miami International Airport', 'United States');
INSERT INTO AIRPORT (CODE, NAME, COUNTRY) VALUES ('SFO', 'San Francisco International', 'United States');
INSERT INTO AIRPORT (CODE, NAME, COUNTRY) VALUES ('JFK', 'John F Kennedy International', 'United States');
INSERT INTO FLIGHTSCHEDULE (FLIGHTSCHEDULEID, FLIGHTNO, DEPARTURETIME, ARRIVALTIME, FIRSTDEPARTURE, LASTDEPARTURE, DEPARTUREAIRPORT_CODE, ARRIVALAIRPORT_CODE) VALUES (1, 'LH410', '11:30:00', '14:35:00', '2011-03-28 11:30:00.0', '2011-05-31', 'MUC', 'JFK');
