package com.sap.core.odata.core.ep;

public class FormatXml {

  public static final String XML_HEADER_NO = "no";
  public static final String XML_HEADER_FULL = "full";
  public static final String XML_HEADER_WITHOUT_ENCODING = "without encoding";
  public static final String XML_BASE = "base";
  public static final String M_PROPERTIES = "properties";
  public static final String M_MIME_TYPE = "MimeType";
  public static final String M_ETAG = "etag";
  public static final String M_COUNT = "count";
  public static final String M_TYPE = "type";
  public static final String M_NULL = "null";
  public static final String D_ELEMENT = "element";
  public static final String D_LINKS = "links";
  public static final String APP_SERVICE = "service";
  public static final String APP_WORKSPACE = "workspace";
  public static final String APP_COLLECTION = "collection";
  public static final String ATOM_FEED = "feed";
  public static final String ATOM_ENTRY = "entry";
  public static final String REL_EDIT = "edit";
  public static final String REL_SELF = "self";
  public static final String REL_EDIT_MEDIA = "edit-media";
  public static final String REL_NEXT = "next";
  public static final String ATOM_LINK = "link";
  public static final String ATOM_REL = "rel";
  public static final String ATOM_HREF = "href";
  public static final String ATOM_TITLE = "title";
  public static final String ATOM_TITLE_DEFAULT = "Default";
  public static final String ATOM_TEXT = "text";
  public static final String ATOM_TYPE = "type";
  public static final String ATOM_UPDATED = "updated";
  public static final String ATOM_ID = "id";
  public static final String ATOM_AUTHOR = "author";
  public static final String ATOM_AUTHOR_NAME = "name";
  public static final String ATOM_AUTHOR_EMAIL = "email";
  public static final String ATOM_AUTHOR_URI = "uri";
  public static final String ATOM_SUMMARY = "summary";
  public static final String ATOM_CONTRIBUTOR = "contributor";
  public static final String ATOM_CONTRIBUTOR_NAME = "name";
  public static final String ATOM_CONTRIBUTOR_EMAIL = "email";
  public static final String ATOM_CONTRIBUTOR_URI = "uri";
  public static final String ATOM_PUBLISHED = "published";
  public static final String ATOM_RIGHTS = "rights";
  public static final String ATOM_CATEGORY = "category";
  public static final String ATOM_CATEGORY_TERM = "term";
  public static final String ATOM_CATEGORY_SCHEME = "scheme";
  public static final String ATOM_CONTENT = "content";
  public static final String ATOM_CONTENT_TYPE = "type";
  public static final String ATOM_CONTENT_SRC = "src";
}
